labels:
  - name: Platform:oCIS
    color: "#02d7e1"
  - name: Platform:oC10
    color: "#02d7e1"
  - name: Platform:iOS
    color: "#02d7e1"
  - name: Platform:Android
    color: "#02d7e1"
  - name: Platform:Web
    color: "#02d7e1"
  - name: Platform:Desktop
    color: "#02d7e1"
  - name: "Deadline-\U0001F4C6"
    color: "#fbca04"
  - name: Estimation:XS(1)
    oldname: Estimation:XS
    color: "#c4fc9c"
  - name: Estimation:S(2)
    oldname: Estimation:S
    color: "#c4fc9c"
  - name: Estimation:M(3)
    oldname: Estimation:M
    color: "#c4fc9c"
  - name: Estimation:L(5)
    oldname: Estimation:L
    color: "#c4fc9c"
  - name: Estimation:XL(8)
    oldname: Estimation:XL
    color: "#c4fc9c"
  - name: Estimation:XXL(13)
    oldname: Estimation:XXL
    color: "#c4fc9c"
  - name: Estimation:XXXL(21)
    oldname: Estimation:XXXL
    color: "#c4fc9c"
  - name: Priority:p1-urgent
    oldname: p1-urgent
    description: Consider a hotfix release with only that fix
    color: "#fc2929"
  - name: Priority:p2-high
    oldname: p2-high
    description: Escalation, on top of current planning, release blocker
    color: "#fc2929"
  - name: Priority:p3-medium
    oldname: p3-medium
    description: Normal priority
    color: "#fc2929"
  - name: Priority:p4-low
    oldname: p4-low
    description: Low priority
    color: "#fc2929"
  - name: QA:ready
    oldname: QA-ready
    color: "#0052cc"
  - name: QA:blocker
    oldname: QA-blocker
    color: "#0052cc"
  - name: QA:known
    oldname: QA-known
    color: "#0052cc"
  - name: QA:testing
    oldname: QA-testing
    color: "#0052cc"
  - name: QA
    color: "#0052cc"
  - name: QA:team
    oldname: QA-team
    color: "#4cc948"
  - name: QA:p1
    oldname: QA-p1
    color: "#fef2c0"
  - name: QA:p2
    oldname: QA-p2
    color: "#fef2c0"
  - name: QA:p3
    oldname: QA-p3
    color: "#fef2c0"
  - name: QA:p4
    oldname: QA-p4
    color: "#fef2c0"
  - name: Severity:sev1-critical
    oldname: sev1-critical
    description: mission critical, total disruption of work, no workaround
    color: "#fc2929"
  - name: Severity:sev2-high
    oldname: sev2-high
    description: operations severely restricted, workaround available
    color: "#fc2929"
  - name: Severity:sev3-medium
    oldname: sev3-medium
    description: minor loss of usage, workaround available
    color: "#fc2929"
  - name: Severity:sev4-low
    oldname: sev4-low
    description: no loss of service, req. for docs info or enhancement
    color: "#fc2929"
  - name: Type:Story
    description: User Story
    color: "#c6f489"
    oldname: story
  - name: Type:Epic
    description: Epic is the parent of user stories
    color: "#6819E7"
    oldname: epic
  - name: Type:Bug
    color: "#fc2929"
    oldname: bug
  - name: Type:Design
    color: "#cc317c"
  - name: Type:Discussion
    color: "#fbca04"
  - name: Type:Technical-Debt
    oldname: technical debt
    color: "#ffff00"
  - name: Type:Orga
    color: "#1D76DB"
  - name: Type:Theme
    color: "#C2E0C6"
  - name: Type:Regression
    color: "#e11d21"
  - name: Type:Knowledge-Base
    description: Solutions for internal knowledge
    color: "#c5def5"
  - name: Type:CI
    oldname: Drone
    description: Related to our Continouus Integration Solution
    color: "#FEF2C0"
  - name: Topic:Transition
    color: "#ccf4ff"
  - name: Topic:Translation
    color: "#ccf4ff"
  - name: Topic:UX-Design
    oldname: design
    color: "#ccf4ff"
  - name: Topic:Packaging
    color: "#ccf4ff"
  - name: Topic:Performance
    color: "#ccf4ff"
  - name: Topic:Hardening
    oldname: Hardening
    color: "#ccf4ff"
  - name: Topic:Security
    color: "#ccf4ff"
  - name: Topic:Docker
    description: Issues related to our official Docker containers
    color: "#ccf4ff"
  - name: Topic:Documentation
    oldname: documentation
    color: "#ccf4ff"
  - name: Topic:Deprecation
    color: "#ccf4ff"
  - name: Topic:Dependencies
    oldname: dependencies
    color: "#ccf4ff"
  - name: Topic:good-first-issue
    oldname: good first issue
    color: "#ccf4ff"
  - name: Topic:API
    color: "#ccf4ff"
  - name: Category:Enhancement
    oldname: enhancement
    description: Add new functionality
    color: "#c5def5"
  - name: Category:Change
    description: Change existing functionality
    color: "#c5def5"
  - name: Category:Defect
    description: Existing functionality is not working as expected
    color: "#c5def5"
  - name: Category:Technical
    description: Technical ehancements
    color: "#c5def5"
  - name: Category:Research
    description: Research is needed
    color: "#c5def5"
  - name: Category:Nonfunctional
    description: Will not change behavior
    color: "#c5def5"
  - name: Status:Waiting-for-Feedback
    color: "#fbca04"
  - name: Status:Bug-Analysis
    color: "#FEF2C0"
  - name: Status:On-Hold
    color: "#aa3109"
  - name: Status:Needs-Review
    oldname: 3 - To Review
    description: Needs review from a maintainer
    color: "#fbca04"
  - name: Status:Needs-Revision
    description: Needs code input from a maintainer
    color: "#fbca04"
  - name: Status:Needs-Info
    color: "#fbca04"
  - name: Status:Needs-release
    oldname: 4 - To release
    color: "#fbca04"
  - name: Status:In-Progress
    oldname: 2 - Developing
    color: "#C5DEF5"
  - name: Status:Completed
    color: "#006B75"
  - name: Status:Blocked
    color: "#990000"
  - name: Status:Pending
    oldname: 1 - To develop
    color: "#eca3a2"
  - name: Status:Proposal
    color: "#D4C5F9"
  - name: Status:Accepted
    color: "#d6f282"
  - name: Status:Wontfix
    oldname: wontfix
    color: "#ffffff"
  - name: Status:Tested
    color: "#62db68"
  - name: Status:Stale
    oldname: status/STALE
    color: "#101000"
  - name: Status:Duplicate
    oldname: duplicate
    color: "#cfd3d7"
  - name: Status:Invalid
    oldname: invalid
    color: "#e4e669"
  - name: Interaction:Needs-help
    oldname: help wanted
    description: Asking some hints to engineering when the issue can't be reproduced
    color: "#fbca04"
  - name: Interaction:Needs-Concept
    color: "#fbca04"
    oldname: needs concept
  - name: Interaction:Needs-tests
    color: "#fbca04"
  - name: Interaction:Question
    oldname: question
    color: "#fbca04"
  - name: Interaction:Discussion
    color: "#fbca04"
  - name: Interaction:Blue-Ticket
    oldname: blue-ticket
    color: "#0033cc"
  - name: Interaction:Minor-Release
    color: "#a5172a"
  - name: Interaction:Bounty
    oldname: bounty
    color: "#129e5e"
