labels:
  - name: Platform:oCIS
    color: "#02d7e1"
  - name: Platform:oC10
    color: "#02d7e1"
  - name: Platform:iOS
    color: "#02d7e1"
  - name: Platform:Android
    color: "#02d7e1"
  - name: Platform:Web
    color: "#02d7e1"
  - name: Platform-Desktop
    color: "#02d7e1"
  - name: "Deadline-\U0001F4C6"
    color: "#ededed"
  - name: Estimation:XS
    color: "#c4fc9c"
  - name: Estimation:S
    color: "#c4fc9c"
  - name: Estimation:M
    color: "#c4fc9c"
  - name: Estimation:L
    color: "#c4fc9c"
  - name: Estimation:XL
    color: "#c4fc9c"
  - name: Estimation:XXL
    color: "#c4fc9c"
  - name: Estimation:XXXL
    color: "#c4fc9c"
  - name: p1-urgent
    description: Consider a hotfix release with only that fix
    color: "#fc2929"
  - name: p2-high
    description: Escalation, on top of current planning, release blocker
    color: "#fc2929"
  - name: p3-medium
    description: Normal priority
    color: "#fc2929"
  - name: p4-low
    description: Low priority
    color: "#fc2929"
  - name: QA-ready
    color: "#5319e7"
  - name: QA-team
    color: "#4cc948"
  - name: QA-p1
    color: "#4cc948"
  - name: QA-p2
    color: "#4cc948"
  - name: QA-p3
    color: "#4cc948"
  - name: QA-p4
    color: "#4cc948"
  - name: sev1-critical
    description: mission critical, total disruption of work, no workaround
    color: "#fc2929"
  - name: sev2-high
    description: operations severely restricted, workaround available
    color: "#fc2929"
  - name: sev3-medium
    description: minor loss of usage, workaround available
    color: "#fc2929"
  - name: sev4-low
    description: no loss of service, req. for docs info or enhancement
    color: "#fc2929"
  - name: Type:Story
    description: User Story
    color: "#c6f489"
  - name: Type:Epic
    description: Epic is the parent of user stories
    color: "#c6f489"
  - name: Type:Bug
    color: "#fc2929"
  - name: Type:Design
    color: "#cc317c"
  - name: Type:Discussion
    color: "#fbca04"
  - name: Type:Technical-Debt
    color: "#ffff00"
  - name: Type:Orga
    color: "#ffff00"
  - name: Type:Theme
    color: "#ededed"
  - name: Type:Regression
    color: "#e11d21"
  - name: Type:Orga
    color: "#c5def5"
  - name: Type:Knowledge-Base
    description: Solutions for internal knowledge
    color: "#c5def5"
  - name: Type:CI
    description: Solutions for internal knowledge
    color: "#c5def5"
  - name: minor-release
    color: "#a5172a"
  - name: Topic:Transition
    color: "#ededed"
  - name: Topic:Translation
    color: "#ededed"
  - name: Topic:UX-Design
    color: "#ccf4ff"
  - name: Topic:Packaging
    color: "#f7c6c7"
  - name: Topic:Performance
    color: "#fbca04"
  - name: Topic:Security
    color: "#d93f0b"
  - name: Topic:Docker
    description: Issues related to our official Docker containers
    color: "#d794ef"
  - name: Topic:Documentation
    color: "#02d7e1"
  - name: Topic:Deprecation
    color: "#e770ef"
  - name: Category:Feature
    description: Add new functionality
    color: "#c5def5"
  - name: Category:Change
    description: Change existing functionality
    color: "#c5def5"
  - name: Category:Defect
    description: Existing functionality is not working as expected
    color: "#c5def5"
  - name: Category:Technical
    description: Technical ehancements
    color: "#c5def5"
  - name: Category:Research
    description: Research is needed
    color: "#c5def5"
  - name: Category:Nonfunctional
    description: Will not change behavior
    color: "#c5def5"
  - name: Status:Waiting-for-Feedback
    color: "#62db68"
  - name: Status:Bug-Analysis
    color: "#fbca04"
  - name: Status:On-Hold
    color: "#e6e6e6"
  - name: Status:Needs-Review
    description: Needs review from a maintainer
    color: "#e6e6e6"
  - name: Status:Needs-Revision
    description: Needs code input from a maintainer
    color: "#e6e6e6"
  - name: Status:Needs-Info
    color: "#0b02e1"
  - name: Status:Needs-release
    color: "#e6e6e6"
  - name: Status:In-Progress
    color: "#e6e6e6"
  - name: Status:Completed
    color: "#e6e6e6"
  - name: Status:Blocked
    color: "#e6e6e6"
  - name: Status:Pending
    color: "#e6e6e6"
  - name: Status:Proposal
    color: "#e6e6e6"
  - name: Status:Accepted
    color: "#e6e6e6"
  - name: Status:Wontfix
    color: "#ffffff"
  - name: Status:Tested
    color: "#fbca04"
  - name: Interaction:Needs-help
    description: Asking some hints to engineering when the issue can't be reproduced
    color: "#3d14e2"
  - name: Interaction:Needs-Concept
    color: "#f78e0e"
  - name: Interaction:Needs-tests
    color: "#a395f9"
  - name: Interaction:Question
    color: "#cc317c"
  - name: Interaction:Blue-Ticket
    color: "#0033cc"
  - name: Imteraction:Minor-Release
    color: "#a5172a"
