labels:
  - name: Platform:oCIS
    color: "#02d7e1"
  - name: Platform:oC10
    color: "#02d7e1"
  - name: Platform:iOS
    color: "#02d7e1"
  - name: Platform:Android
    color: "#02d7e1"
  - name: Platform:Web
    color: "#02d7e1"
  - name: Platform:Desktop
    color: "#02d7e1"
  - name: "Deadline-\U0001F4C6"
    color: "#fbca04"
  - name: Estimation:XS(1)
    color: "#c4fc9c"
  - name: Estimation:S(2)
    color: "#c4fc9c"
  - name: Estimation:M(3)
    color: "#c4fc9c"
  - name: Estimation:L(5)
    color: "#c4fc9c"
  - name: Estimation:XL(8)
    color: "#c4fc9c"
  - name: Estimation:XXL(13)
    color: "#c4fc9c"
  - name: Estimation:XXXL(21)
    color: "#c4fc9c"
  - name: p1-urgent
    description: Consider a hotfix release with only that fix
    color: "#fc2929"
  - name: p2-high
    description: Escalation, on top of current planning, release blocker
    color: "#fc2929"
  - name: p3-medium
    description: Normal priority
    color: "#fc2929"
  - name: p4-low
    description: Low priority
    color: "#fc2929"
  - name: QA-ready
    color: "#5319e7"
  - name: QA-team
    color: "#4cc948"
  - name: QA-p1
    color: "#4cc948"
  - name: QA-p2
    color: "#4cc948"
  - name: QA-p3
    color: "#4cc948"
  - name: QA-p4
    color: "#4cc948"
  - name: sev1-critical
    description: mission critical, total disruption of work, no workaround
    color: "#fc2929"
  - name: sev2-high
    description: operations severely restricted, workaround available
    color: "#fc2929"
  - name: sev3-medium
    description: minor loss of usage, workaround available
    color: "#fc2929"
  - name: sev4-low
    description: no loss of service, req. for docs info or enhancement
    color: "#fc2929"
  - name: Type:Story
    description: User Story
    color: "#c6f489"
    oldname: story
  - name: Type:Epic
    description: Epic is the parent of user stories
    color: "#6819E7"
    oldname: epic
  - name: Type:Bug
    color: "#fc2929"
    oldname: bug
  - name: Type:Design
    color: "#cc317c"
  - name: Type:Discussion
    color: "#fbca04"
  - name: Type:Technical-Debt
    color: "#ffff00"
  - name: Type:Orga
    color: "#1D76DB"
  - name: Type:Theme
    color: "#C2E0C6"
  - name: Type:Regression
    color: "#e11d21"
  - name: Type:Knowledge-Base
    description: Solutions for internal knowledge
    color: "#c5def5"
  - name: Type:CI
    description: Related to our Continouus Integration Solution
    color: "#FEF2C0"
  - name: Topic:Transition
    color: "#ccf4ff"
  - name: Topic:Translation
    color: "#ccf4ff"
  - name: Topic:UX-Design
    color: "#ccf4ff"
  - name: Topic:Packaging
    color: "#ccf4ff"
  - name: Topic:Performance
    color: "#ccf4ff"
  - name: Topic:Security
    color: "#ccf4ff"
  - name: Topic:Docker
    description: Issues related to our official Docker containers
    color: "#ccf4ff"
  - name: Topic:Documentation
    color: "#ccf4ff"
  - name: Topic:Deprecation
    color: "#ccf4ff"
  - name: Topic:Good-First-Issue
    color: "#7057ff"
  - name: Topic:API
    color: "#a2eeef"
  - name: Category:Feature
    description: Add new functionality
    color: "#c5def5"
  - name: Category:Change
    description: Change existing functionality
    color: "#c5def5"
  - name: Category:Defect
    description: Existing functionality is not working as expected
    color: "#c5def5"
  - name: Category:Technical
    description: Technical ehancements
    color: "#c5def5"
  - name: Category:Research
    description: Research is needed
    color: "#c5def5"
  - name: Category:Nonfunctional
    description: Will not change behavior
    color: "#c5def5"
  - name: Status:Waiting-for-Feedback
    color: "#fbca04"
  - name: Status:Bug-Analysis
    color: "#FEF2C0"
  - name: Status:On-Hold
    color: "#aa3109"
  - name: Status:Needs-Review
    description: Needs review from a maintainer
    color: "#fbca04"
  - name: Status:Needs-Revision
    description: Needs code input from a maintainer
    color: "#fbca04"
  - name: Status:Needs-Info
    color: "#fbca04"
  - name: Status:Needs-release
    color: "#fbca04"
  - name: Status:In-Progress
    color: "#C5DEF5"
  - name: Status:Completed
    color: "#006B75"
  - name: Status:Blocked
    color: "#990000"
  - name: Status:Pending
    color: "#eca3a2"
  - name: Status:Proposal
    color: "#D4C5F9"
  - name: Status:Accepted
    color: "#d6f282"
  - name: Status:Wontfix
    color: "#ffffff"
  - name: Status:Tested
    color: "#62db68"
  - name: Status:Stale
    color: "#101000"
  - name: Interaction:Needs-help
    description: Asking some hints to engineering when the issue can't be reproduced
    color: "#fbca04"
  - name: Interaction:Needs-Concept
    color: "#fbca04"
    oldname: needs concept
  - name: Interaction:Needs-tests
    color: "#fbca04"
  - name: Interaction:Question
    color: "#fbca04"
  - name: Interaction:Discussion
    color: "#fbca04"
  - name: Interaction:Blue-Ticket
    color: "#0033cc"
  - name: Interaction:Minor-Release
    color: "#a5172a"
