labels:
  - name: blue-ticket
    color: "#0033cc"
  - name: bug-analysis
    color: "#fbca04"
  - name: bug-solved
    color: "#0e8a16"
  - name: bug
    color: "#fc2929"
  - name: Platform:oCIS
    color: "#02d7e1"
  - name: Platform:oC10
    color: "#02d7e1"
  - name: Platform:iOS
    color: "#02d7e1"
  - name: Platform:Android
    color: "#02d7e1"
  - name: Platform:Web
    color: "#02d7e1"
  - name: Platform-Desktop
    color: "#02d7e1"
  - name: Consulting
    color: "#639fed"
  - name: Customer-FR
    color: "#d93f0b"
  - name: "Deadline-\U0001F4C6"
    color: "#ededed"
  - name: Deployment
    color: "#d86763"
  - name: deprecation
    color: "#e770ef"
  - name: Design
    color: "#cc317c"
  - name: discussion
    color: "#fbca04"
  - name: docker
    description: Issues related to our official Docker containers
    color: "#d794ef"
  - name: documentation
    color: "#02d7e1"
  - name: Enhancement
    color: "#84b6eb"
  - name: epic
    color: "#fbca04"
  - name: Estimation-XS
    color: "#c4fc9c"
  - name: Estimation-S
    color: "#c4fc9c"
  - name: Estimation-M
    color: "#c4fc9c"
  - name: Estimation-L
    color: "#c4fc9c"
  - name: Estimation-XL
    color: "#c4fc9c"
  - name: Estimation-XXL
    color: "#c4fc9c"
  - name: Estimation-XXXL
    color: "#c4fc9c"
  - name: Knowledge-Base
    description: Solutions for internal knowledge
    color: "#c5def5"
  - name: minor-release
    color: "#a5172a"
  - name: needs-concept
    color: "#f78e0e"
  - name: needs-dev-tickets
    color: "#0e8a16"
  - name: needs-info
    color: "#0b02e1"
  - name: needs-tests
    color: "#a395f9"
  - name: needs engineering help
    description: Asking some hints to engineering when the issue can't be reproduced
    color: "#3d14e2"
  - name: OCIS-Fastlane
    color: "#ededed"
  - name: orga
    color: "#c5def5"
  - name: p1-urgent
    description: 'Consider a hotfix release with only that fix (ex: lose trust, money,
      security issue, ...)'
    color: "#fc2929"
  - name: p2-high
    description: Escalation, on top of current planning, release blocker
    color: "#fc2929"
  - name: p3-medium
    description: Normal priority
    color: "#fc2929"
  - name: p4-low
    description: Low priority
    color: "#fc2929"
  - name: packaging
    color: "#f7c6c7"
  - name: performance
    color: "#fbca04"
  - name: project
    color: "#0052cc"
  - name: QA-ready
    color: "#5319e7"
  - name: QA-team
    color: "#4cc948"
  - name: QA
    color: "#1d76db"
  - name: question
    color: "#cc317c"
  - name: Ready-for-Sprint
    color: "#0e8a16"
  - name: Regression
    color: "#e11d21"
  - name: research
    color: "#ffff00"
  - name: security
    color: "#d93f0b"
  - name: server-sprint
    color: "#fef2c0"
  - name: server
    color: "#bfdadc"
  - name: sev1-critical
    description: mission critical, total disruption of work, no workaround
    color: "#fc2929"
  - name: sev2-high
    description: operations severely restricted, workaround available
    color: "#fc2929"
  - name: sev3-medium
    description: minor loss of usage, workaround available
    color: "#fc2929"
  - name: sev4-low
    description: no loss of service, req. for docs info or enhancement
    color: "#fc2929"
  - name: story
    description: User Story
    color: "#c6f489"
  - name: TAM
    color: "#d3ff35"
  - name: technical debt
    color: "#ffff00"
  - name: tentative
    color: "#e5272a"
  - name: tested
    color: "#fbca04"
  - name: theme
    color: "#ededed"
  - name: Transition
    color: "#ededed"
  - name: translation
    color: "#ededed"
  - name: triage
    color: "#00ffff"
  - name: Tutorial
    color: "#ededed"
  - name: U1-Feature
    description: User Story Category
    color: "#c5def5"
  - name: U2-Change
    description: User Story Category
    color: "#c5def5"
  - name: U3-Defect
    description: User Story Category
    color: "#c5def5"
  - name: U4-Technical
    description: User Story Category
    color: "#c5def5"
  - name: U5-Knowledge-Acquisition
    description: User Story Category
    color: "#c5def5"
  - name: U6-Nonfunctional
    description: User Story Category
    color: "#c5def5"
  - name: UX-Design
    color: "#ccf4ff"
  - name: waiting-for-feedback
    color: "#62db68"
  - name: waiting
    color: "#e6e6e6"
  - name: wontfix
    color: "#ffffff"
